#include <Windows.h>


namespace Report
{
	void SendReport(DWORD reportCode);
}

enum reports
{
	INVALID_ANTICHEAT_START = 1,
	CANNOT_QUEUE_APCS,
	MANUALMAPPED_MODULE,
	HOOK_DETECTED,
	DEBUGGER_DETECTED,
	BLACKLISTED_DLL_DETECTED,
	ODD_BAHAVIOR,
	OVERLAY_DETECTED,
	RIP_OUTSIDE_VALID_MODULE
};